-- Cleanup previous failed roster loads
USE DATABASE MINING_DB;
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE MINING_WH;

TRUNCATE TABLE OPS_REF.SHIFT_INSTANCES;
TRUNCATE TABLE OPS_REF.OPERATOR_SHIFT_ASSIGNMENTS;
TRUNCATE TABLE OPS_HIST.MAINTENANCE_RECORDS;
